// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Url           string
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type Payment struct {
	ID             int32
	Email          string
	StripeChargeID string
	Amount         int64
	Currency       string
	Status         string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Post struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
	IsValid   sql.NullBool
}

type Refund struct {
	ID             int32
	Email          string
	StripeRefundID string
	PaymentID      sql.NullInt32
	Amount         int64
	Status         string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	PasswordHash string
	Email        string
	IsVerified   sql.NullBool
}

type UserSession struct {
	ID        int32
	UserID    uuid.NullUUID
	SessionID uuid.UUID
	CreatedAt sql.NullTime
	ExpiresAt time.Time
	IsValid   sql.NullBool
}
