-- +goose Up
ALTER TABLE users 
    DROP COLUMN name,
    DROP COLUMN api_key,
    ADD COLUMN username VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN password_hash TEXT NOT NULL,
    ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN is_verified BOOLEAN DEFAULT FALSE,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE users 
    ADD COLUMN name TEXT NOT NULL,
    ADD COLUMN COLUMN api_key VARCHAR(64) UNIQUE NOT NULL DEFAULT,
    DROP COLUMN username,
    DROP COLUMN password_hash,
    DROP COLUMN email,
    DROP COLUMN is_verified,
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT;